[package]
name = "lapce-rust"
version = "0.3.1896"
edition = "2021"

[dependencies]
anyhow = "1.0"
flate2 = "1.0.22"
serde_json = "1.0.59"
serde = { version = "1.0", features = ["derive"] }
lapce-plugin = "0.1.1"
